### PR TITLE
Privacy.md

### PR DESCRIPTION
**Pull request by HarryHeights**
Here's the privacy policy as discussed. It's pretty much basic and very suitable for TEdit but don't take my word for it, please proof read and let me know if there are mistakes so I can correct them.

### CODE REVIEW

**Comment by ATryder** [comment]
Looks great thanks. I have a couple of changes I'd like to be made if you wouldn't mind:

Line 7: Change "peculiar" to "particular"

Line 11: Remove "as possible" and change "However, to enable TEdit read text files" to "However, to enable TEdit to read text files".

Line 38: Change "doesn't" to "don't"

**Comment by HarryHeights** [comment]
Alright. I'll make changes right away. I think for line 38 though, "does not" is a better word to use there.

**Comment by HarryHeights** [comment]
Changes made. You can review again.

**Comment by ATryder** [comment]
Thanks so much Harry, this is really great!

**Comment by HarryHeights** [comment]
You are welcome. Glad I could be of service.

**Pull request merged**
